CREATE DATABASE IF NOT EXISTS SENSORS;

USE SENSORS;

CREATE TABLE IF NOT EXISTS TEMPERATURE (
    SENSOR_ID VARCHAR(50),
    RECORDED_TIMESTAMP DATETIME NOT NULL,
    MEASURE FLOAT NOT NULL,
    PRIMARY KEY (SENSOR_ID, RECORDED_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS HUMIDITY (
    SENSOR_ID VARCHAR(50),
    RECORDED_TIMESTAMP DATETIME NOT NULL,
    MEASURE FLOAT NOT NULL,
    PRIMARY KEY (SENSOR_ID, RECORDED_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS LUMINOSITY (
    SENSOR_ID VARCHAR(50),
    RECORDED_TIMESTAMP DATETIME NOT NULL,
    MEASURE FLOAT NOT NULL,
    PRIMARY KEY (SENSOR_ID, RECORDED_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS TEMPERATURE_ALERTS (
    SENSOR_ID VARCHAR(50),
    RECORDED_TIMESTAMP DATETIME NOT NULL,
    ALERT VARCHAR(500) NOT NULL,
    PRIMARY KEY (SENSOR_ID, RECORDED_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS HUMIDITY_ALERTS (
    SENSOR_ID VARCHAR(50),
    RECORDED_TIMESTAMP DATETIME NOT NULL,
    ALERT VARCHAR(500) NOT NULL,
    PRIMARY KEY (SENSOR_ID, RECORDED_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS LUMINOSITY_ALERTS (
    SENSOR_ID VARCHAR(50),
    RECORDED_TIMESTAMP DATETIME NOT NULL,
    ALERT VARCHAR(500) NOT NULL,
    PRIMARY KEY (SENSOR_ID, RECORDED_TIMESTAMP)
);
